<?php
namespace EDAM\Types;

/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

/**
 * An enumeration defining the possible states of a BusinessInvitation.
 * 
 * APPROVED: The invitation was created or approved by a business admin and may be redeemed by the
 *   invited email.
 * 
 * REQUESTED: The invitation was requested by a non-admin member of the business and must be
 *   approved by an admin before it may be redeemed. Invitations in this state do not count
 *   against a business' seat limit.
 * 
 * REDEEMED: The invitation has already been redeemed. Invitations in this state do not count
 *   against a business' seat limit.
 */
final class BusinessInvitationStatus
{
    const APPROVED = 0;

    const REQUESTED = 1;

    const REDEEMED = 2;

    static public $__names = array(
        0 => 'APPROVED',
        1 => 'REQUESTED',
        2 => 'REDEEMED',
    );
}

