<?php
namespace EDAM\Types;

/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

/**
 * Enumeration of the roles that a User can have within an Evernote Business account.
 * 
 * ADMIN: The user is an administrator of the Evernote Business account.
 * 
 * NORMAL: The user is a regular user within the Evernote Business account.
 */
final class BusinessUserRole
{
    const ADMIN = 1;

    const NORMAL = 2;

    static public $__names = array(
        1 => 'ADMIN',
        2 => 'NORMAL',
    );
}

