<?php
namespace EDAM\Types;

/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

/**
 * The BusinessUserStatus indicates the status of the user in the business.
 * 
 * A BusinessUser will typically start as ACTIVE.
 * Only ACTIVE users can authenticate to the Business.
 * 
 * <dl>
 * <dt>ACTIVE<dt>
 * <dd>The business user can authenticate to and access the business.</dd>
 * <dt>DEACTIVATED<dt>
 * <dd>The business user has been deactivated and cannot access the business</dd>
 * </dl>
 */
final class BusinessUserStatus
{
    const ACTIVE = 1;

    const DEACTIVATED = 2;

    static public $__names = array(
        1 => 'ACTIVE',
        2 => 'DEACTIVATED',
    );
}

