<?php
namespace EDAM\Types;

/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

/**
 * This enumeration defines the possible sort ordering for notes when
 * they are returned from a search result.
 */
final class NoteSortOrder
{
    const CREATED = 1;

    const UPDATED = 2;

    const RELEVANCE = 3;

    const UPDATE_SEQUENCE_NUMBER = 4;

    const TITLE = 5;

    static public $__names = array(
        1 => 'CREATED',
        2 => 'UPDATED',
        3 => 'RELEVANCE',
        4 => 'UPDATE_SEQUENCE_NUMBER',
        5 => 'TITLE',
    );
}

