<?php
namespace EDAM\Types;

/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

/**
 * This enumeration defines the possible permission levels for a user.
 * Free accounts will have a level of NORMAL and paid Premium accounts
 * will have a level of PREMIUM.
 */
final class PrivilegeLevel
{
    const NORMAL = 1;

    const PREMIUM = 3;

    const VIP = 5;

    const MANAGER = 7;

    const SUPPORT = 8;

    const ADMIN = 9;

    static public $__names = array(
        1 => 'NORMAL',
        3 => 'PREMIUM',
        5 => 'VIP',
        7 => 'MANAGER',
        8 => 'SUPPORT',
        9 => 'ADMIN',
    );
}

