<?php
namespace EDAM\Types;

/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

/**
 * This enumeration defines the possible states that a notebook can be in for a recipient.
 * It encompasses the "inMyList" boolean and default notebook status.
 * 
 * <dl>
 * <dt>NOT_IN_MY_LIST</dt>
 * <dd>The notebook is not in the recipient's list (not "joined").</dd>
 * <dt>IN_MY_LIST</dt>
 * <dd>The notebook is in the recipient's notebook list (formerly, we would say
 *     that the recipient has "joined" the notebook)</dd>
 * <dt>IN_MY_LIST_AND_DEFAULT_NOTEBOOK</dt>
 * <dd>The same as IN_MY_LIST and this notebook is the user's default notebook.</dd>
 * </dl>
 */
final class RecipientStatus
{
    const NOT_IN_MY_LIST = 1;

    const IN_MY_LIST = 2;

    const IN_MY_LIST_AND_DEFAULT_NOTEBOOK = 3;

    static public $__names = array(
        1 => 'NOT_IN_MY_LIST',
        2 => 'IN_MY_LIST',
        3 => 'IN_MY_LIST_AND_DEFAULT_NOTEBOOK',
    );
}

