<?php
namespace EDAM\Types;

/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

/**
 * This enumeration defines the possible types of related content.
 * 
 * NEWS_ARTICLE: This related content is a news article
 * PROFILE_PERSON: This match refers to the profile of an individual person
 * PROFILE_ORGANIZATION: This match refers to the profile of an organization
 * REFERENCE_MATERIAL: This related content is material from reference works
 */
final class RelatedContentType
{
    const NEWS_ARTICLE = 1;

    const PROFILE_PERSON = 2;

    const PROFILE_ORGANIZATION = 3;

    const REFERENCE_MATERIAL = 4;

    static public $__names = array(
        1 => 'NEWS_ARTICLE',
        2 => 'PROFILE_PERSON',
        3 => 'PROFILE_ORGANIZATION',
        4 => 'REFERENCE_MATERIAL',
    );
}

