<?php
namespace EDAM\Types;

/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

/**
 * Privilege levels for accessing a shared note. All privilege levels convey "activity feed" access,
 * which allows the recipient to access information about other recipients and the activity stream.
 * 
 * READ_NOTE: Recipient has rights to read the shared note.
 * 
 * MODIFY_NOTE: Recipient has all of the rights of READ_NOTE, plus rights to modify the shared
 *   note's content, title and resources. Other fields, including the notebook, tags and metadata,
 *   may not be modified.
 * 
 * FULL_ACCESS: Recipient has all of the rights of MODIFY_NOTE, plus rights to share the note with
 *   other users via email, public note links, and note sharing. Recipient may also update and
 *   remove other recipient's note sharing rights.
 */
final class SharedNotePrivilegeLevel
{
    const READ_NOTE = 0;

    const MODIFY_NOTE = 1;

    const FULL_ACCESS = 2;

    static public $__names = array(
        0 => 'READ_NOTE',
        1 => 'MODIFY_NOTE',
        2 => 'FULL_ACCESS',
    );
}

