<?php
namespace EDAM\UserStore;

/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class UserStore_completeTwoFactorAuthentication_args
{
    static public $isValidate = false;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'authenticationToken',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
        2 => array(
            'var' => 'oneTimeCode',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
        3 => array(
            'var' => 'deviceIdentifier',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
        4 => array(
            'var' => 'deviceDescription',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
    );

    /**
     * @var string
     */
    public $authenticationToken = null;
    /**
     * @var string
     */
    public $oneTimeCode = null;
    /**
     * @var string
     */
    public $deviceIdentifier = null;
    /**
     * @var string
     */
    public $deviceDescription = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['authenticationToken'])) {
                $this->authenticationToken = $vals['authenticationToken'];
            }
            if (isset($vals['oneTimeCode'])) {
                $this->oneTimeCode = $vals['oneTimeCode'];
            }
            if (isset($vals['deviceIdentifier'])) {
                $this->deviceIdentifier = $vals['deviceIdentifier'];
            }
            if (isset($vals['deviceDescription'])) {
                $this->deviceDescription = $vals['deviceDescription'];
            }
        }
    }

    public function getName()
    {
        return 'UserStore_completeTwoFactorAuthentication_args';
    }


    public function read($input)
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $xfer += $input->readStructBegin($fname);
        while (true) {
            $xfer += $input->readFieldBegin($fname, $ftype, $fid);
            if ($ftype == TType::STOP) {
                break;
            }
            switch ($fid) {
                case 1:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->authenticationToken);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 2:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->oneTimeCode);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 3:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->deviceIdentifier);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 4:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->deviceDescription);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                default:
                    $xfer += $input->skip($ftype);
                    break;
            }
            $xfer += $input->readFieldEnd();
        }
        $xfer += $input->readStructEnd();
        return $xfer;
    }

    public function write($output)
    {
        $xfer = 0;
        $xfer += $output->writeStructBegin('UserStore_completeTwoFactorAuthentication_args');
        if ($this->authenticationToken !== null) {
            $xfer += $output->writeFieldBegin('authenticationToken', TType::STRING, 1);
            $xfer += $output->writeString($this->authenticationToken);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->oneTimeCode !== null) {
            $xfer += $output->writeFieldBegin('oneTimeCode', TType::STRING, 2);
            $xfer += $output->writeString($this->oneTimeCode);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->deviceIdentifier !== null) {
            $xfer += $output->writeFieldBegin('deviceIdentifier', TType::STRING, 3);
            $xfer += $output->writeString($this->deviceIdentifier);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->deviceDescription !== null) {
            $xfer += $output->writeFieldBegin('deviceDescription', TType::STRING, 4);
            $xfer += $output->writeString($this->deviceDescription);
            $xfer += $output->writeFieldEnd();
        }
        $xfer += $output->writeFieldStop();
        $xfer += $output->writeStructEnd();
        return $xfer;
    }
}
