<?php
namespace EDAM\NoteStore;

/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

/**
 *  A small structure for returning a list of notes out of a larger set.
 * 
 * <dl>
 *  <dt>startIndex</dt>
 *    <dd>
 *    The starting index within the overall set of notes.  This
 *    is also the number of notes that are "before" this list in the set.
 *    </dd>
 * 
 *  <dt>totalNotes</dt>
 *    <dd>
 *    The number of notes in the larger set.  This can be used
 *    to calculate how many notes are "after" this note in the set.
 *    (I.e.  remaining = totalNotes - (startIndex + notes.length)  )
 *    </dd>
 * 
 *  <dt>notes</dt>
 *    <dd>
 *    The list of notes from this range.  The Notes will include all
 *    metadata (attributes, resources, etc.), but will not include the ENML
 *    content of the note or the binary contents of any resources.
 *    </dd>
 * 
 *  <dt>stoppedWords</dt>
 *    <dd>
 *    If the NoteList was produced using a text based search
 *    query that included words that are not indexed or searched by the service,
 *    this will include a list of those ignored words.
 *    </dd>
 * 
 *  <dt>searchedWords</dt>
 *    <dd>
 *    If the NoteList was produced using a text based search
 *    query that included viable search words or quoted expressions, this will
 *    include a list of those words.  Any stopped words will not be included
 *    in this list.
 *    </dd>
 * 
 *  <dt>updateCount</dt>
 *    <dd>
 *    Indicates the total number of transactions that have
 *    been committed within the account.  This reflects (for example) the
 *    number of discrete additions or modifications that have been made to
 *    the data in this account (tags, notes, resources, etc.).
 *    This number is the "high water mark" for Update Sequence Numbers (USN)
 *    within the account.
 *    </dd>
 * 
 *  <dt>searchContextBytes</dt>
 *    <dd>
 *    Specifies the correlating information about the current search session, in byte array.
 *    </dd>
 *  </dl>
 * 
 *  <dt>debugInfo</dt>
 *    <dd>
 *    Depends on the value of <code>context</code> in NoteFilter, this field
 *    may contain debug information if the service decides to do so.
 *    </dd>
 * 
 */
class NoteList
{
    static public $isValidate = false;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'startIndex',
            'isRequired' => true,
            'type' => TType::I32,
        ),
        2 => array(
            'var' => 'totalNotes',
            'isRequired' => true,
            'type' => TType::I32,
        ),
        3 => array(
            'var' => 'notes',
            'isRequired' => true,
            'type' => TType::LST,
            'etype' => TType::STRUCT,
            'elem' => array(
                'type' => TType::STRUCT,
                'class' => '\EDAM\Types\Note',
                ),
        ),
        4 => array(
            'var' => 'stoppedWords',
            'isRequired' => false,
            'type' => TType::LST,
            'etype' => TType::STRING,
            'elem' => array(
                'type' => TType::STRING,
                ),
        ),
        5 => array(
            'var' => 'searchedWords',
            'isRequired' => false,
            'type' => TType::LST,
            'etype' => TType::STRING,
            'elem' => array(
                'type' => TType::STRING,
                ),
        ),
        6 => array(
            'var' => 'updateCount',
            'isRequired' => false,
            'type' => TType::I32,
        ),
        7 => array(
            'var' => 'searchContextBytes',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
        8 => array(
            'var' => 'debugInfo',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
    );

    /**
     * @var int
     */
    public $startIndex = null;
    /**
     * @var int
     */
    public $totalNotes = null;
    /**
     * @var \EDAM\Types\Note[]
     */
    public $notes = null;
    /**
     * @var string[]
     */
    public $stoppedWords = null;
    /**
     * @var string[]
     */
    public $searchedWords = null;
    /**
     * @var int
     */
    public $updateCount = null;
    /**
     * @var string
     */
    public $searchContextBytes = null;
    /**
     * @var string
     */
    public $debugInfo = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['startIndex'])) {
                $this->startIndex = $vals['startIndex'];
            }
            if (isset($vals['totalNotes'])) {
                $this->totalNotes = $vals['totalNotes'];
            }
            if (isset($vals['notes'])) {
                $this->notes = $vals['notes'];
            }
            if (isset($vals['stoppedWords'])) {
                $this->stoppedWords = $vals['stoppedWords'];
            }
            if (isset($vals['searchedWords'])) {
                $this->searchedWords = $vals['searchedWords'];
            }
            if (isset($vals['updateCount'])) {
                $this->updateCount = $vals['updateCount'];
            }
            if (isset($vals['searchContextBytes'])) {
                $this->searchContextBytes = $vals['searchContextBytes'];
            }
            if (isset($vals['debugInfo'])) {
                $this->debugInfo = $vals['debugInfo'];
            }
        }
    }

    public function getName()
    {
        return 'NoteList';
    }


    public function read($input)
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $xfer += $input->readStructBegin($fname);
        while (true) {
            $xfer += $input->readFieldBegin($fname, $ftype, $fid);
            if ($ftype == TType::STOP) {
                break;
            }
            switch ($fid) {
                case 1:
                    if ($ftype == TType::I32) {
                        $xfer += $input->readI32($this->startIndex);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 2:
                    if ($ftype == TType::I32) {
                        $xfer += $input->readI32($this->totalNotes);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 3:
                    if ($ftype == TType::LST) {
                        $this->notes = array();
                        $_size92 = 0;
                        $_etype95 = 0;
                        $xfer += $input->readListBegin($_etype95, $_size92);
                        for ($_i96 = 0; $_i96 < $_size92; ++$_i96) {
                            $elem97 = null;
                            $elem97 = new \EDAM\Types\Note();
                            $xfer += $elem97->read($input);
                            $this->notes []= $elem97;
                        }
                        $xfer += $input->readListEnd();
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 4:
                    if ($ftype == TType::LST) {
                        $this->stoppedWords = array();
                        $_size98 = 0;
                        $_etype101 = 0;
                        $xfer += $input->readListBegin($_etype101, $_size98);
                        for ($_i102 = 0; $_i102 < $_size98; ++$_i102) {
                            $elem103 = null;
                            $xfer += $input->readString($elem103);
                            $this->stoppedWords []= $elem103;
                        }
                        $xfer += $input->readListEnd();
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 5:
                    if ($ftype == TType::LST) {
                        $this->searchedWords = array();
                        $_size104 = 0;
                        $_etype107 = 0;
                        $xfer += $input->readListBegin($_etype107, $_size104);
                        for ($_i108 = 0; $_i108 < $_size104; ++$_i108) {
                            $elem109 = null;
                            $xfer += $input->readString($elem109);
                            $this->searchedWords []= $elem109;
                        }
                        $xfer += $input->readListEnd();
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 6:
                    if ($ftype == TType::I32) {
                        $xfer += $input->readI32($this->updateCount);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 7:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->searchContextBytes);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 8:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->debugInfo);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                default:
                    $xfer += $input->skip($ftype);
                    break;
            }
            $xfer += $input->readFieldEnd();
        }
        $xfer += $input->readStructEnd();
        return $xfer;
    }

    public function write($output)
    {
        $xfer = 0;
        $xfer += $output->writeStructBegin('NoteList');
        if ($this->startIndex !== null) {
            $xfer += $output->writeFieldBegin('startIndex', TType::I32, 1);
            $xfer += $output->writeI32($this->startIndex);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->totalNotes !== null) {
            $xfer += $output->writeFieldBegin('totalNotes', TType::I32, 2);
            $xfer += $output->writeI32($this->totalNotes);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->notes !== null) {
            if (!is_array($this->notes)) {
                throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
            }
            $xfer += $output->writeFieldBegin('notes', TType::LST, 3);
            $output->writeListBegin(TType::STRUCT, count($this->notes));
            foreach ($this->notes as $iter110) {
                $xfer += $iter110->write($output);
            }
            $output->writeListEnd();
            $xfer += $output->writeFieldEnd();
        }
        if ($this->stoppedWords !== null) {
            if (!is_array($this->stoppedWords)) {
                throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
            }
            $xfer += $output->writeFieldBegin('stoppedWords', TType::LST, 4);
            $output->writeListBegin(TType::STRING, count($this->stoppedWords));
            foreach ($this->stoppedWords as $iter111) {
                $xfer += $output->writeString($iter111);
            }
            $output->writeListEnd();
            $xfer += $output->writeFieldEnd();
        }
        if ($this->searchedWords !== null) {
            if (!is_array($this->searchedWords)) {
                throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
            }
            $xfer += $output->writeFieldBegin('searchedWords', TType::LST, 5);
            $output->writeListBegin(TType::STRING, count($this->searchedWords));
            foreach ($this->searchedWords as $iter112) {
                $xfer += $output->writeString($iter112);
            }
            $output->writeListEnd();
            $xfer += $output->writeFieldEnd();
        }
        if ($this->updateCount !== null) {
            $xfer += $output->writeFieldBegin('updateCount', TType::I32, 6);
            $xfer += $output->writeI32($this->updateCount);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->searchContextBytes !== null) {
            $xfer += $output->writeFieldBegin('searchContextBytes', TType::STRING, 7);
            $xfer += $output->writeString($this->searchContextBytes);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->debugInfo !== null) {
            $xfer += $output->writeFieldBegin('debugInfo', TType::STRING, 8);
            $xfer += $output->writeString($this->debugInfo);
            $xfer += $output->writeFieldEnd();
        }
        $xfer += $output->writeFieldStop();
        $xfer += $output->writeStructEnd();
        return $xfer;
    }
}
